name: Testing Workflow

on: 
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: say hello
        run: echo "Hello My name is Obinna"
        run: echo "This is my first CI pipeline"
