name: Testing Workflow

on: 
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: say hello
        run: | 
          echo "Hello My name is Obinna"
          echo "I am so happy to be writing my first workflow"
        
